// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNFpOeYxiFACUv6AYR4RxmREL_Ssm8LP0',
    appId: '1:591561989240:android:7b4420204b18eaeb13218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SFr4WuGvM_o7cKaQ83kiSAa3cEUjHP0',
    appId: '1:591561989240:ios:3ae4ca46c4856d6313218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
    androidClientId: '591561989240-bugrms4dvf9ult0kgvt8arcmkmmo743g.apps.googleusercontent.com',
    iosClientId: '591561989240-opjpaklu936k4pmn0rvij7jn2tmosphj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLViczRyoa_wK8hA6paRbpI_LxZpavsvI',
    appId: '1:591561989240:web:7294a84d2a6e259b13218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    authDomain: 'fruits-hub-27b09.firebaseapp.com',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
    measurementId: 'G-FW54H1Z225',
  );
}
